READING DATASET

In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt

In [4]:
df_c = pd.read_csv("flo_data_20k.csv")

In [5]:
df = df_c.copy()

In [6]:
df["master_id"].nunique()

19945

Understanding and Preparing Data

In [5]:
df

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12
0,cc294636-19f0-11eb-8d74-000d3a38a36f,Android App,Offline,2020-10-30,2021-02-26,2021-02-21,2021-02-26,4.0,1.0,139.99,799.38,[KADIN]
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,Android App,Mobile,2017-02-08,2021-02-16,2021-02-16,2020-01-10,19.0,2.0,159.97,1853.58,"[ERKEK, COCUK, KADIN, AKTIFSPOR]"
2,69b69676-1a40-11ea-941b-000d3a38a36f,Android App,Android App,2019-11-27,2020-11-27,2020-11-27,2019-12-01,3.0,2.0,189.97,395.35,"[ERKEK, KADIN]"
3,1854e56c-491f-11eb-806e-000d3a38a36f,Android App,Android App,2021-01-06,2021-01-17,2021-01-17,2021-01-06,1.0,1.0,39.99,81.98,"[AKTIFCOCUK, COCUK]"
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,Desktop,Desktop,2019-08-03,2021-03-07,2021-03-07,2019-08-03,1.0,1.0,49.99,159.99,[AKTIFSPOR]
...,...,...,...,...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,Android App,Offline,2019-09-21,2020-07-05,2020-06-05,2020-07-05,1.0,2.0,289.98,111.98,"[ERKEK, AKTIFSPOR]"
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,Desktop,Desktop,2020-03-01,2020-12-22,2020-12-22,2020-03-01,1.0,1.0,150.48,239.99,[AKTIFSPOR]
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,Ios App,Ios App,2019-09-11,2021-05-24,2021-05-24,2019-09-11,2.0,1.0,139.98,492.96,[AKTIFSPOR]
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,Android App,Android App,2019-03-27,2021-02-13,2021-02-13,2021-01-08,1.0,5.0,711.79,297.98,"[ERKEK, AKTIFSPOR]"
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,Android App,Android App,2019-09-03,2020-06-06,2020-06-06,2019-09-03,1.0,1.0,39.99,221.98,"[KADIN, AKTIFSPOR]"

In [6]:
for col_name in df.columns: 
    print(col_name)

master_id
order_channel
last_order_channel
first_order_date
last_order_date
last_order_date_online
last_order_date_offline
order_num_total_ever_online
order_num_total_ever_offline
customer_value_total_ever_offline
customer_value_total_ever_online
interested_in_categories_12

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
order_num_total_ever_online,19945.0,3.110855,4.225647,1.00,1.00,2.00,4.00,200.00
order_num_total_ever_offline,19945.0,1.913913,2.062880,1.00,1.00,1.00,2.00,109.00
customer_value_total_ever_offline,19945.0,253.922597,301.532853,10.00,99.99,179.98,319.97,18119.14
customer_value_total_ever_online,19945.0,497.321690,832.601886,12.99,149.98,286.46,578.44,45220.13

In [8]:
df.isnull().sum()

master_id                            0
order_channel                        0
last_order_channel                   0
first_order_date                     0
last_order_date                      0
last_order_date_online               0
last_order_date_offline              0
order_num_total_ever_online          0
order_num_total_ever_offline         0
customer_value_total_ever_offline    0
customer_value_total_ever_online     0
interested_in_categories_12          0
dtype: int64

In [9]:
df.dtypes

master_id                             object
order_channel                         object
last_order_channel                    object
first_order_date                      object
last_order_date                       object
last_order_date_online                object
last_order_date_offline               object
order_num_total_ever_online          float64
order_num_total_ever_offline         float64
customer_value_total_ever_offline    float64
customer_value_total_ever_online     float64
interested_in_categories_12           object
dtype: object

In [10]:
df["total_order_num_ever"] = df["order_num_total_ever_online"] + df["order_num_total_ever_offline"]
df["total_customer_value_ever"] = (df["order_num_total_ever_offline"]* df["customer_value_total_ever_offline"]) + (df["order_num_total_ever_online"]* df["customer_value_total_ever_online"])

In [11]:
df

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,total_order_num_ever,total_customer_value_ever
0,cc294636-19f0-11eb-8d74-000d3a38a36f,Android App,Offline,2020-10-30,2021-02-26,2021-02-21,2021-02-26,4.0,1.0,139.99,799.38,[KADIN],5.0,3337.51
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,Android App,Mobile,2017-02-08,2021-02-16,2021-02-16,2020-01-10,19.0,2.0,159.97,1853.58,"[ERKEK, COCUK, KADIN, AKTIFSPOR]",21.0,35537.96
2,69b69676-1a40-11ea-941b-000d3a38a36f,Android App,Android App,2019-11-27,2020-11-27,2020-11-27,2019-12-01,3.0,2.0,189.97,395.35,"[ERKEK, KADIN]",5.0,1565.99
3,1854e56c-491f-11eb-806e-000d3a38a36f,Android App,Android App,2021-01-06,2021-01-17,2021-01-17,2021-01-06,1.0,1.0,39.99,81.98,"[AKTIFCOCUK, COCUK]",2.0,121.97
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,Desktop,Desktop,2019-08-03,2021-03-07,2021-03-07,2019-08-03,1.0,1.0,49.99,159.99,[AKTIFSPOR],2.0,209.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,Android App,Offline,2019-09-21,2020-07-05,2020-06-05,2020-07-05,1.0,2.0,289.98,111.98,"[ERKEK, AKTIFSPOR]",3.0,691.94
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,Desktop,Desktop,2020-03-01,2020-12-22,2020-12-22,2020-03-01,1.0,1.0,150.48,239.99,[AKTIFSPOR],2.0,390.47
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,Ios App,Ios App,2019-09-11,2021-05-24,2021-05-24,2019-09-11,2.0,1.0,139.98,492.96,[AKTIFSPOR],3.0,1125.90
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,Android App,Android App,2019-03-27,2021-02-13,2021-02-13,2021-01-08,1.0,5.0,711.79,297.98,"[ERKEK, AKTIFSPOR]",6.0,3856.93
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,Android App,Android App,2019-09-03,2020-06-06,2020-06-06,2019-09-03,1.0,1.0,39.99,221.98,"[KADIN, AKTIFSPOR]",2.0,261.97

In [12]:
df.dtypes

master_id                             object
order_channel                         object
last_order_channel                    object
first_order_date                      object
last_order_date                       object
last_order_date_online                object
last_order_date_offline               object
order_num_total_ever_online          float64
order_num_total_ever_offline         float64
customer_value_total_ever_offline    float64
customer_value_total_ever_online     float64
interested_in_categories_12           object
total_order_num_ever                 float64
total_customer_value_ever            float64
dtype: object

In [13]:
import datetime as dt

In [14]:
df['first_order_date'] = pd.to_datetime(df['first_order_date'])
df['last_order_date'] = pd.to_datetime(df['last_order_date'])
df['last_order_date_online'] = pd.to_datetime(df['last_order_date_online'])
df['last_order_date_offline'] = pd.to_datetime(df['last_order_date_offline'])

In [15]:
df.dtypes

master_id                                    object
order_channel                                object
last_order_channel                           object
first_order_date                     datetime64[ns]
last_order_date                      datetime64[ns]
last_order_date_online               datetime64[ns]
last_order_date_offline              datetime64[ns]
order_num_total_ever_online                 float64
order_num_total_ever_offline                float64
customer_value_total_ever_offline           float64
customer_value_total_ever_online            float64
interested_in_categories_12                  object
total_order_num_ever                        float64
total_customer_value_ever                   float64
dtype: object

In [16]:
def q1(x):
    return x.quantile(0.25)
def q2(x):
    return x.quantile(0.5)

def q3(x):
    return x.quantile(0.75)

def q4(x):
    return x.quantile(0.99)



df.groupby("order_channel").agg({"master_id" : "count", "total_order_num_ever": ["min","max","mean","sum",q1,q2,q3,q4] , "total_customer_value_ever" : ["min","max","mean","sum",q1,q2,q3,q4]})

              master_id total_order_num_ever                                 \
                  count                  min    max      mean      sum   q1
order_channel
Android App        9495                  2.0  202.0  5.504897  52269.0  3.0
Desktop            2735                  2.0   70.0  3.992687  10920.0  2.0
Ios App            2833                  2.0   83.0  5.418637  15351.0  3.0
Mobile             4882                  2.0   77.0  4.440598  21679.0  2.0

                               total_customer_value_ever              \
                q2   q3     q4                       min         max
order_channel
Android App    4.0  6.0  24.00                     55.98  9045395.94
Desktop        3.0  5.0  16.00                     44.98  1164967.46
Ios App        4.0  6.0  25.68                     69.98  2646265.30
Mobile         3.0  5.0  20.00                     44.98   451814.05

                                                                     \
                      mean          sum      q1       q2         q3
order_channel
Android App    6705.581994  63669501.03  561.57  1438.77  3921.4600
Desktop        2678.354110   7325298.49  369.89   743.65  1722.0950
Ios App        7073.810900  20040106.28  609.95  1446.34  3799.0800
Mobile         3145.226536  15354995.95  377.95   859.83  2146.8275


                       q4
order_channel
Android App    67952.3946
Desktop        28641.9540
Ios App        88741.5456
Mobile         37579.8391

In [17]:
df["master_id"].nunique()

19945

In [18]:
df.shape

(19945, 14)

In [19]:
df.sort_values( by= "total_customer_value_ever", ascending = False).head(10)

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,total_order_num_ever,total_customer_value_ever
11150,5d1c466a-9cfd-11e9-9897-000d3a38a36f,Android App,Desktop,2013-10-11,2021-04-30,2021-04-30,2020-12-24,200.0,2.0,684.97,45220.13,"[AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]",202.0,9045395.94
7613,73fd19aa-9e37-11e9-9897-000d3a38a36f,Ios App,Offline,2014-01-14,2021-05-18,2021-01-30,2021-05-18,81.0,1.0,1263.76,32654.34,"[ERKEK, COCUK, KADIN, AKTIFSPOR]",82.0,2646265.30
4315,d5ef8058-a5c6-11e9-a2fc-000d3a38a36f,Android App,Android App,2018-08-06,2021-02-23,2021-02-23,2020-07-06,67.0,1.0,130.49,36687.80,"[AKTIFCOCUK, ERKEK, KADIN, AKTIFSPOR]",68.0,2458213.09
7223,cba59206-9dd1-11e9-9897-000d3a38a36f,Android App,Android App,2013-02-21,2021-05-09,2021-05-09,2020-01-25,130.0,1.0,49.99,12232.25,"[AKTIFCOCUK, ERKEK, KADIN, AKTIFSPOR]",131.0,1590242.49
7330,a4d534a2-5b1b-11eb-8dbd-000d3a38a36f,Desktop,Desktop,2020-02-16,2021-04-30,2021-04-30,2020-12-18,66.0,4.0,843.68,17599.89,"[ERKEK, KADIN, AKTIFSPOR]",70.0,1164967.46
8068,d696c654-2633-11ea-8e1c-000d3a38a36f,Ios App,Ios App,2017-05-10,2021-04-13,2021-04-13,2019-08-15,69.0,1.0,82.48,16836.09,"[AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]",70.0,1161772.69
8783,a57f4302-b1a8-11e9-89fa-000d3a38a36f,Android App,Offline,2019-08-07,2020-11-04,2020-09-07,2020-11-04,2.0,109.0,10239.46,143.98,"[AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]",111.0,1116389.10
2619,fdbe8304-a7ab-11e9-a2fc-000d3a38a36f,Android App,Offline,2018-10-18,2020-06-30,2018-10-18,2020-06-30,1.0,87.0,8432.25,139.98,[ERKEK],88.0,733745.73
163,fef57ffa-aae6-11e9-a2fc-000d3a38a36f,Mobile,Desktop,2016-11-08,2021-05-12,2021-05-12,2020-07-09,36.0,1.0,180.73,12545.37,"[ERKEK, AKTIFSPOR]",37.0,451814.05
6337,f7e2335e-a7c4-11e9-a2fc-000d3a38a36f,Ios App,Mobile,2015-11-23,2020-08-08,2020-08-08,2020-06-26,54.0,7.0,820.33,7133.14,"[COCUK, KADIN]",61.0,390931.87

In [20]:
df.sort_values( by= "total_order_num_ever", ascending = False).head(10)

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,total_order_num_ever,total_customer_value_ever
11150,5d1c466a-9cfd-11e9-9897-000d3a38a36f,Android App,Desktop,2013-10-11,2021-04-30,2021-04-30,2020-12-24,200.0,2.0,684.97,45220.13,"[AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]",202.0,9045395.94
7223,cba59206-9dd1-11e9-9897-000d3a38a36f,Android App,Android App,2013-02-21,2021-05-09,2021-05-09,2020-01-25,130.0,1.0,49.99,12232.25,"[AKTIFCOCUK, ERKEK, KADIN, AKTIFSPOR]",131.0,1590242.49
8783,a57f4302-b1a8-11e9-89fa-000d3a38a36f,Android App,Offline,2019-08-07,2020-11-04,2020-09-07,2020-11-04,2.0,109.0,10239.46,143.98,"[AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]",111.0,1116389.10
2619,fdbe8304-a7ab-11e9-a2fc-000d3a38a36f,Android App,Offline,2018-10-18,2020-06-30,2018-10-18,2020-06-30,1.0,87.0,8432.25,139.98,[ERKEK],88.0,733745.73
6322,329968c6-a0e2-11e9-a2fc-000d3a38a36f,Ios App,Ios App,2019-02-14,2021-04-05,2021-04-05,2020-02-17,2.0,81.0,3997.55,242.81,[ERKEK],83.0,324287.17
7613,73fd19aa-9e37-11e9-9897-000d3a38a36f,Ios App,Offline,2014-01-14,2021-05-18,2021-01-30,2021-05-18,81.0,1.0,1263.76,32654.34,"[ERKEK, COCUK, KADIN, AKTIFSPOR]",82.0,2646265.30
9347,44d032ee-a0d4-11e9-a2fc-000d3a38a36f,Mobile,Mobile,2019-02-11,2021-02-11,2021-02-11,2020-12-24,3.0,74.0,4640.77,543.28,"[KADIN, AKTIFSPOR]",77.0,345046.82
10954,b27e241a-a901-11e9-a2fc-000d3a38a36f,Mobile,Mobile,2015-09-12,2021-04-01,2021-04-01,2019-10-08,72.0,3.0,292.93,5004.95,"[AKTIFCOCUK, ERKEK, KADIN, AKTIFSPOR]",75.0,361235.19
8068,d696c654-2633-11ea-8e1c-000d3a38a36f,Ios App,Ios App,2017-05-10,2021-04-13,2021-04-13,2019-08-15,69.0,1.0,82.48,16836.09,"[AKTIFCOCUK, ERKEK, COCUK, KADIN, AKTIFSPOR]",70.0,1161772.69
7330,a4d534a2-5b1b-11eb-8dbd-000d3a38a36f,Desktop,Desktop,2020-02-16,2021-04-30,2021-04-30,2020-12-18,66.0,4.0,843.68,17599.89,"[ERKEK, KADIN, AKTIFSPOR]",70.0,1164967.46

In [21]:

print("##############################")
print(df.groupby("order_channel").agg({"master_id" : "count", "total_order_num_ever": ["min","max","mean","sum",q1,q2,q3,q4] , "total_customer_value_ever" : ["min","max","mean","sum",q1,q2,q3,q4]}))

##############################
              master_id total_order_num_ever                                 \
                  count                  min    max      mean      sum   q1
order_channel
Android App        9495                  2.0  202.0  5.504897  52269.0  3.0
Desktop            2735                  2.0   70.0  3.992687  10920.0  2.0
Ios App            2833                  2.0   83.0  5.418637  15351.0  3.0
Mobile             4882                  2.0   77.0  4.440598  21679.0  2.0

                               total_customer_value_ever              \
                q2   q3     q4                       min         max
order_channel
Android App    4.0  6.0  24.00                     55.98  9045395.94
Desktop        3.0  5.0  16.00                     44.98  1164967.46
Ios App        4.0  6.0  25.68                     69.98  2646265.30
Mobile         3.0  5.0  20.00                     44.98   451814.05

                                                                     \
                      mean          sum      q1       q2         q3
order_channel
Android App    6705.581994  63669501.03  561.57  1438.77  3921.4600
Desktop        2678.354110   7325298.49  369.89   743.65  1722.0950
Ios App        7073.810900  20040106.28  609.95  1446.34  3799.0800
Mobile         3145.226536  15354995.95  377.95   859.83  2146.8275


                       q4
order_channel
Android App    67952.3946
Desktop        28641.9540
Ios App        88741.5456
Mobile         37579.8391

In [22]:
def Data_preparation_process (dataframe ,head =10) :
    print("Shape : ",dataframe.shape)
    print("##############################")
    print("Col_names")
    for col_name in dataframe.columns: 
        print(col_name)
    print("##############################")
    print("First_ten_index_: \n", dataframe.head(head))
    print("##############################")
    print("Null_values : \n", dataframe.isnull().sum())
    print("##############################")
    print("Types of columns : \n",df.dtypes)
    print("##############################")
    print("Statistics : \n",dataframe.describe().T)
    print("##############################")
    print("Object type to date type start")
    dataframe['first_order_date'] = pd.to_datetime(dataframe['first_order_date'])
    dataframe['last_order_date'] = pd.to_datetime(dataframe['last_order_date'])
    dataframe['last_order_date_online'] = pd.to_datetime(dataframe['last_order_date_online'])
    dataframe['last_order_date_offline'] = pd.to_datetime(dataframe['last_order_date_offline'])
    print("Object type to date type finish")
    print("##############################")
    dataframe["total_order_num_ever"] = dataframe["order_num_total_ever_online"] + dataframe["order_num_total_ever_offline"]
    dataframe["total_customer_value_ever"] = (dataframe["order_num_total_ever_offline"]* dataframe["customer_value_total_ever_offline"]) + (dataframe["order_num_total_ever_online"]* dataframe["customer_value_total_ever_online"])
    print("total_order_num_ever and total_customer_value_ever added")
    print("##############################")
    print("statistics for order_channel :")
    def q1(x):
        return x.quantile(0.25)
    def q2(x):
        return x.quantile(0.5)

    def q3(x):
        return x.quantile(0.75)

    def q4(x):
        return x.quantile(0.99)



    print(dataframe.groupby("order_channel").agg({"master_id" : "count", "total_order_num_ever": ["min","max","mean","sum",q1,q2,q3,q4] , "total_customer_value_ever" : ["min","max","mean","sum",q1,q2,q3,q4]}))
    print("##############################")
    print("Top 10 customers who spend the most")
    print(dataframe.sort_values( by= "total_customer_value_ever", ascending = False).head(head))
    print("##############################")
    print("Top 10 customers who spend the most frequently")
    print(dataframe.sort_values( by= "total_order_num_ever", ascending = False).head(head))

RFM SCORES

In [23]:
today_date = dt.datetime(2021,6,2)

In [24]:
df["recency"] = df.apply(lambda x: (today_date-x["last_order_date"]).days, axis=1)
df["frequency"] = df["total_order_num_ever"]
df["monetary"] = df["total_customer_value_ever"]

In [25]:
df

,master_id,order_channel,last_order_channel,first_order_date,last_order_date,last_order_date_online,last_order_date_offline,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,total_order_num_ever,total_customer_value_ever,recency,frequency,monetary
0,cc294636-19f0-11eb-8d74-000d3a38a36f,Android App,Offline,2020-10-30,2021-02-26,2021-02-21,2021-02-26,4.0,1.0,139.99,799.38,[KADIN],5.0,3337.51,96,5.0,3337.51
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,Android App,Mobile,2017-02-08,2021-02-16,2021-02-16,2020-01-10,19.0,2.0,159.97,1853.58,"[ERKEK, COCUK, KADIN, AKTIFSPOR]",21.0,35537.96,106,21.0,35537.96
2,69b69676-1a40-11ea-941b-000d3a38a36f,Android App,Android App,2019-11-27,2020-11-27,2020-11-27,2019-12-01,3.0,2.0,189.97,395.35,"[ERKEK, KADIN]",5.0,1565.99,187,5.0,1565.99
3,1854e56c-491f-11eb-806e-000d3a38a36f,Android App,Android App,2021-01-06,2021-01-17,2021-01-17,2021-01-06,1.0,1.0,39.99,81.98,"[AKTIFCOCUK, COCUK]",2.0,121.97,136,2.0,121.97
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,Desktop,Desktop,2019-08-03,2021-03-07,2021-03-07,2019-08-03,1.0,1.0,49.99,159.99,[AKTIFSPOR],2.0,209.98,87,2.0,209.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,Android App,Offline,2019-09-21,2020-07-05,2020-06-05,2020-07-05,1.0,2.0,289.98,111.98,"[ERKEK, AKTIFSPOR]",3.0,691.94,332,3.0,691.94
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,Desktop,Desktop,2020-03-01,2020-12-22,2020-12-22,2020-03-01,1.0,1.0,150.48,239.99,[AKTIFSPOR],2.0,390.47,162,2.0,390.47
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,Ios App,Ios App,2019-09-11,2021-05-24,2021-05-24,2019-09-11,2.0,1.0,139.98,492.96,[AKTIFSPOR],3.0,1125.90,9,3.0,1125.90
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,Android App,Android App,2019-03-27,2021-02-13,2021-02-13,2021-01-08,1.0,5.0,711.79,297.98,"[ERKEK, AKTIFSPOR]",6.0,3856.93,109,6.0,3856.93
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,Android App,Android App,2019-09-03,2020-06-06,2020-06-06,2019-09-03,1.0,1.0,39.99,221.98,"[KADIN, AKTIFSPOR]",2.0,261.97,361,2.0,261.97

In [26]:
rfm = df.filter(["master_id",'recency','frequency','monetary'], axis=1)

In [27]:
rfm

                                  master_id  recency  frequency  monetary
0      cc294636-19f0-11eb-8d74-000d3a38a36f       96        5.0   3337.51
1      f431bd5a-ab7b-11e9-a2fc-000d3a38a36f      106       21.0  35537.96
2      69b69676-1a40-11ea-941b-000d3a38a36f      187        5.0   1565.99
3      1854e56c-491f-11eb-806e-000d3a38a36f      136        2.0    121.97
4      d6ea1074-f1f5-11e9-9346-000d3a38a36f       87        2.0    209.98
...                                     ...      ...        ...       ...
19940  727e2b6e-ddd4-11e9-a848-000d3a38a36f      332        3.0    691.94
19941  25cd53d4-61bf-11ea-8dd8-000d3a38a36f      162        2.0    390.47
19942  8aea4c2a-d6fc-11e9-93bc-000d3a38a36f        9        3.0   1125.90
19943  e50bb46c-ff30-11e9-a5e8-000d3a38a36f      109        6.0   3856.93
19944  740998d2-b1f7-11e9-89fa-000d3a38a36f      361        2.0    261.97

[19945 rows x 4 columns]

CALCULATING RFM SCORES

In [28]:
rfm["recency_score"] = pd.qcut(rfm["recency"], 5, labels= [5,4,3,2,1])
rfm["frequency_score"] = pd.qcut(rfm["frequency"].rank(method = "first"), 5, labels= [1,2,3,4,5])
rfm["monetary_score"] = pd.qcut(rfm["monetary"], 5, labels= [1,2,3,4,5])

In [29]:
rfm

,master_id,recency,frequency,monetary,recency_score,frequency_score,monetary_score
0,cc294636-19f0-11eb-8d74-000d3a38a36f,96,5.0,3337.51,3,4,4
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,106,21.0,35537.96,3,5,5
2,69b69676-1a40-11ea-941b-000d3a38a36f,187,5.0,1565.99,2,4,3
3,1854e56c-491f-11eb-806e-000d3a38a36f,136,2.0,121.97,3,1,1
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,87,2.0,209.98,3,1,1
...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,332,3.0,691.94,1,3,2
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,162,2.0,390.47,2,2,2
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,9,3.0,1125.90,5,3,3
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,109,6.0,3856.93,3,4,4
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,361,2.0,261.97,1,2,1

In [30]:
rfm["RF_SCORE"] = (rfm["recency_score"].astype(str)+ rfm["frequency_score"].astype(str))

In [31]:
rfm

,master_id,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RF_SCORE
0,cc294636-19f0-11eb-8d74-000d3a38a36f,96,5.0,3337.51,3,4,4,34
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,106,21.0,35537.96,3,5,5,35
2,69b69676-1a40-11ea-941b-000d3a38a36f,187,5.0,1565.99,2,4,3,24
3,1854e56c-491f-11eb-806e-000d3a38a36f,136,2.0,121.97,3,1,1,31
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,87,2.0,209.98,3,1,1,31
...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,332,3.0,691.94,1,3,2,13
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,162,2.0,390.47,2,2,2,22
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,9,3.0,1125.90,5,3,3,53
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,109,6.0,3856.93,3,4,4,34
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,361,2.0,261.97,1,2,1,12

In [32]:
seg_map = {
    r'[1-2][1-2]': 'hibernating',
    r'[1-2][3-4]': 'at_Risk',
    r'[1-2]5': 'cant_loose',
    r'3[1-2]': 'about_to_sleep',
    r'33': 'need_attention',
    r'[3-4][4-5]': 'loyal_customers',
    r'41': 'promising',
    r'51': 'new_customers',
    r'[4-5][2-3]': 'potential_loyalists',
    r'5[4-5]': 'champions'}

In [33]:
rfm['segment'] = rfm['RF_SCORE'].replace(seg_map, regex=True)

In [34]:
rfm

,master_id,recency,frequency,monetary,recency_score,frequency_score,monetary_score,RF_SCORE,segment
0,cc294636-19f0-11eb-8d74-000d3a38a36f,96,5.0,3337.51,3,4,4,34,loyal_customers
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,106,21.0,35537.96,3,5,5,35,loyal_customers
2,69b69676-1a40-11ea-941b-000d3a38a36f,187,5.0,1565.99,2,4,3,24,at_Risk
3,1854e56c-491f-11eb-806e-000d3a38a36f,136,2.0,121.97,3,1,1,31,about_to_sleep
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,87,2.0,209.98,3,1,1,31,about_to_sleep
...,...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,332,3.0,691.94,1,3,2,13,at_Risk
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,162,2.0,390.47,2,2,2,22,hibernating
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,9,3.0,1125.90,5,3,3,53,potential_loyalists
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,109,6.0,3856.93,3,4,4,34,loyal_customers
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,361,2.0,261.97,1,2,1,12,hibernating

STATISTICS OF SEGMENTS

In [35]:
rfm.groupby("segment").agg(["mean","max","min"]).drop("RF_SCORE",axis=1)

C:\Users\90535\AppData\Local\Temp\ipykernel_22620\1734638186.py:1: FutureWarning: ['master_id', 'recency_score', 'frequency_score', 'monetary_score'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  rfm.groupby("segment").agg(["mean","max","min"]).drop("RF_SCORE",axis=1)

                        recency            frequency              \
                           mean  max  min       mean    max  min
segment
about_to_sleep       114.785144  146   85   2.401473    3.0  2.0
at_Risk              242.606835  368  147   4.472373    7.0  3.0
cant_loose           236.444167  368  147  10.698333  111.0  7.0
champions             18.106625   34    3   8.934265  202.0  4.0
hibernating          248.949501  368  147   2.394007    3.0  2.0
loyal_customers       83.594763  146   35   8.374591   83.0  4.0
need_attention       114.828676  146   85   3.727825    4.0  3.0
new_customers         18.917647   34    3   2.000000    2.0  2.0
potential_loyalists   38.155888   84    3   3.304289    4.0  2.0
promising             59.921175   84   35   2.000000    2.0  2.0

                         monetary
                             mean         max      min
segment
about_to_sleep         474.771234     2571.89    49.98
at_Risk               1830.985701    14222.71   131.95
cant_loose           16012.137417  1116389.10  1097.68
champions            19388.445983  9045395.94   620.88
hibernating            486.054653     4985.34    44.98
loyal_customers      10987.894040  2458213.09   400.92
need_attention        1230.975711    12904.34   141.73
new_customers          339.955544     1725.38    69.98
potential_loyalists   1043.956698    56944.62    65.91
promising              335.672705     1671.75    44.98

LISTING THE NECESSARY CUSTOMERS

In [36]:
new_df = pd.merge(rfm, df, on='master_id', how='inner')

In [37]:
new_df

,master_id,recency_x,frequency_x,monetary_x,recency_score,frequency_score,monetary_score,RF_SCORE,segment,order_channel,...,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,total_order_num_ever,total_customer_value_ever,recency_y,frequency_y,monetary_y
0,cc294636-19f0-11eb-8d74-000d3a38a36f,96,5.0,3337.51,3,4,4,34,loyal_customers,Android App,...,4.0,1.0,139.99,799.38,[KADIN],5.0,3337.51,96,5.0,3337.51
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,106,21.0,35537.96,3,5,5,35,loyal_customers,Android App,...,19.0,2.0,159.97,1853.58,"[ERKEK, COCUK, KADIN, AKTIFSPOR]",21.0,35537.96,106,21.0,35537.96
2,69b69676-1a40-11ea-941b-000d3a38a36f,187,5.0,1565.99,2,4,3,24,at_Risk,Android App,...,3.0,2.0,189.97,395.35,"[ERKEK, KADIN]",5.0,1565.99,187,5.0,1565.99
3,1854e56c-491f-11eb-806e-000d3a38a36f,136,2.0,121.97,3,1,1,31,about_to_sleep,Android App,...,1.0,1.0,39.99,81.98,"[AKTIFCOCUK, COCUK]",2.0,121.97,136,2.0,121.97
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,87,2.0,209.98,3,1,1,31,about_to_sleep,Desktop,...,1.0,1.0,49.99,159.99,[AKTIFSPOR],2.0,209.98,87,2.0,209.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,332,3.0,691.94,1,3,2,13,at_Risk,Android App,...,1.0,2.0,289.98,111.98,"[ERKEK, AKTIFSPOR]",3.0,691.94,332,3.0,691.94
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,162,2.0,390.47,2,2,2,22,hibernating,Desktop,...,1.0,1.0,150.48,239.99,[AKTIFSPOR],2.0,390.47,162,2.0,390.47
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,9,3.0,1125.90,5,3,3,53,potential_loyalists,Ios App,...,2.0,1.0,139.98,492.96,[AKTIFSPOR],3.0,1125.90,9,3.0,1125.90
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,109,6.0,3856.93,3,4,4,34,loyal_customers,Android App,...,1.0,5.0,711.79,297.98,"[ERKEK, AKTIFSPOR]",6.0,3856.93,109,6.0,3856.93
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,361,2.0,261.97,1,2,1,12,hibernating,Android App,...,1.0,1.0,39.99,221.98,"[KADIN, AKTIFSPOR]",2.0,261.97,361,2.0,261.97

In [80]:
customer_list_1 = new_df[(new_df["segment"] == "champions") | (new_df["segment"] == "loyal_customers")]

In [83]:
customer_list_1 = customer_list_1[customer_list_1["interested_in_categories_12"].str.contains("KADIN")]

In [84]:
customer_list_1.to_csv("customer_list_1.csv")

B PART

In [85]:
new_df

,master_id,recency_x,frequency_x,monetary_x,recency_score,frequency_score,monetary_score,RF_SCORE,segment,order_channel,...,order_num_total_ever_online,order_num_total_ever_offline,customer_value_total_ever_offline,customer_value_total_ever_online,interested_in_categories_12,total_order_num_ever,total_customer_value_ever,recency_y,frequency_y,monetary_y
0,cc294636-19f0-11eb-8d74-000d3a38a36f,96,5.0,3337.51,3,4,4,34,loyal_customers,Android App,...,4.0,1.0,139.99,799.38,[KADIN],5.0,3337.51,96,5.0,3337.51
1,f431bd5a-ab7b-11e9-a2fc-000d3a38a36f,106,21.0,35537.96,3,5,5,35,loyal_customers,Android App,...,19.0,2.0,159.97,1853.58,"[ERKEK, COCUK, KADIN, AKTIFSPOR]",21.0,35537.96,106,21.0,35537.96
2,69b69676-1a40-11ea-941b-000d3a38a36f,187,5.0,1565.99,2,4,3,24,at_Risk,Android App,...,3.0,2.0,189.97,395.35,"[ERKEK, KADIN]",5.0,1565.99,187,5.0,1565.99
3,1854e56c-491f-11eb-806e-000d3a38a36f,136,2.0,121.97,3,1,1,31,about_to_sleep,Android App,...,1.0,1.0,39.99,81.98,"[AKTIFCOCUK, COCUK]",2.0,121.97,136,2.0,121.97
4,d6ea1074-f1f5-11e9-9346-000d3a38a36f,87,2.0,209.98,3,1,1,31,about_to_sleep,Desktop,...,1.0,1.0,49.99,159.99,[AKTIFSPOR],2.0,209.98,87,2.0,209.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19940,727e2b6e-ddd4-11e9-a848-000d3a38a36f,332,3.0,691.94,1,3,2,13,at_Risk,Android App,...,1.0,2.0,289.98,111.98,"[ERKEK, AKTIFSPOR]",3.0,691.94,332,3.0,691.94
19941,25cd53d4-61bf-11ea-8dd8-000d3a38a36f,162,2.0,390.47,2,2,2,22,hibernating,Desktop,...,1.0,1.0,150.48,239.99,[AKTIFSPOR],2.0,390.47,162,2.0,390.47
19942,8aea4c2a-d6fc-11e9-93bc-000d3a38a36f,9,3.0,1125.90,5,3,3,53,potential_loyalists,Ios App,...,2.0,1.0,139.98,492.96,[AKTIFSPOR],3.0,1125.90,9,3.0,1125.90
19943,e50bb46c-ff30-11e9-a5e8-000d3a38a36f,109,6.0,3856.93,3,4,4,34,loyal_customers,Android App,...,1.0,5.0,711.79,297.98,"[ERKEK, AKTIFSPOR]",6.0,3856.93,109,6.0,3856.93
19944,740998d2-b1f7-11e9-89fa-000d3a38a36f,361,2.0,261.97,1,2,1,12,hibernating,Android App,...,1.0,1.0,39.99,221.98,"[KADIN, AKTIFSPOR]",2.0,261.97,361,2.0,261.97

In [87]:
customer_list_2 = new_df[(new_df["segment"] == "about_to_sleep") | (new_df["segment"] == "cant_loose")| (new_df["segment"] == "new_customers")]

In [94]:
customer_list_2 = customer_list_2[(customer_list_2["interested_in_categories_12"].str.contains("ERKEK"))|(customer_list_2["interested_in_categories_12"].str.contains("COCUK"))]

In [95]:
customer_list_2.to_csv("customer_list_2.csv")